CREATE TABLE IF NOT EXISTS `improved_review` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ELEMENT_ID` int(18) NOT NULL,
  `APPROVED` char(1) NOT NULL DEFAULT 'Y',
  `USER_ID` int(18) DEFAULT NULL,
  `SITE_ID` char(2) NOT NULL,
  `AUTHOR_ID` int(10) DEFAULT NULL,
  `AUTHOR_NAME` varchar(255) DEFAULT NULL,
  `AUTHOR_EMAIL` varchar(255) DEFAULT NULL,
  `AUTHOR_IP` varchar(255) DEFAULT NULL,
  `POST_DATE` datetime NOT NULL,
  `MESSAGE_PLUS` text,
  `MESSAGE_PLUS_HTML` text,
  `MESSAGE_MINUS` text,
  `MESSAGE_MINUS_HTML` text,
  `MESSAGE` text,
  `MESSAGE_HTML` text,
  `TITLE` varchar(255) DEFAULT NULL,
  `REPLY` text,
  `REPLY_HTML` text,
  `IS_SEND` char(1) NOT NULL DEFAULT 'N',
  `VOTE_MINUS` int(10) DEFAULT '0',
  `VOTE_PLUS` int(10) DEFAULT '0',
  `RATING` int(1) DEFAULT '0',
  `ONLY_RATING` char(1) NOT NULL DEFAULT 'N',
  `IS_BEST` char(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`ID`),
  KEY `IX_REVIEW_MESSAGE_AUTHOR` (`AUTHOR_ID`)
);

CREATE TABLE IF NOT EXISTS `improved_review_complaint` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DATE_CREATE` datetime NOT NULL,
  `REVIEW_ID` int(18) NOT NULL,
  `USER_ID` int(18) NOT NULL,
  `ACTIVE` char(1) NOT NULL DEFAULT 'Y',
  `MESSAGE` text,
  `SENDER_NAME` varchar(255) NOT NULL,
  `SENDER_EMAIL` varchar(255) NOT NULL,
  `SENDER_IP` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `improved_review_file` (
  `ID` int(18) NOT NULL AUTO_INCREMENT,
  `REVIEW_ID` int(18) NOT NULL,
  `FILE_ID` int(18) NOT NULL,
  `USER_ID` int(18) DEFAULT NULL,
  `ELEMENT_ID` int(18) NOT NULL,
  `TIMESTAMP_X` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `HITS` int(18) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IX_REVIEW_FILE_FILE` (`FILE_ID`),
  KEY `IX_REVIEW_FILE` (`REVIEW_ID`)
);

CREATE TABLE IF NOT EXISTS `improved_review_rating2element` (
  `TIMESTAMP_X` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `USER_ID` int(18) DEFAULT NULL,
  `ELEMENT_ID` int(18) NOT NULL,
  `IP` varchar(15) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `improved_review_subs` (
  `ELEMENT_ID` int(18) NOT NULL,
  `EMAIL` varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS `improved_review_user` (
  `ID` int(18) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(18) DEFAULT NULL,
  `ALLOW_POST` char(1) NOT NULL DEFAULT 'Y',
  `MODERATE_POST` char(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `improved_review_vote_to_review` (
  `TIMESTAMP_X` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `USER_ID` int(18) NOT NULL,
  `REVIEW_ID` int(18) NOT NULL,
  `IP` varchar(15) DEFAULT NULL
);